"""Regression tests for confirmed bugs, generated by the Quality Playbook.

BUG-001: an explicitly empty upload platform include list must enable all
supported platforms in the shared workflow, never zero platforms.

Regenerated for the 0.5.0 layered-configuration contract. The workflow stops
at the pre-upload review gate (`execute_job` transitions upload to
``awaiting_review``); the platform selection itself is applied by
``JobService.submit_upload`` when the accepted draft is submitted, so the
empty-include behavior is asserted at that boundary. Processing and upload
boundaries are mocked; no credentials or network are used.
"""

import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from clipmorph.job import JobManifest
from clipmorph.platforms import SUPPORTED_PLATFORMS
from clipmorph.service import JobService
from clipmorph.workflow import _enabled_platforms


class Bug001RegressionTests(unittest.TestCase):
    def test_workflow_empty_platform_include_resolves_to_all_platforms(self):
        self.assertEqual(
            _enabled_platforms({"platforms": {"include": []}}),
            list(SUPPORTED_PLATFORMS))
        self.assertEqual(
            _enabled_platforms({"platforms": {}}), list(SUPPORTED_PLATFORMS))

    def test_empty_platform_include_enables_all_platforms(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            source = Path(temp_dir) / "input.mp4"
            source.write_bytes(b"video")
            data_dir = Path(temp_dir)
            jobs_dir = data_dir / "jobs"

            configuration = {
                "general": {"source": "input.mp4"},
                "conversion": {"skip": True, "subtitles": {"skip": True}},
                "upload": {
                    "content": {"title": "Regression clip"},
                    "platforms": {"include": []},
                },
            }
            manifest = JobManifest.create(str(source), configuration, jobs_dir)
            source_artifact = manifest.source_path
            manifest.set_artifact(source_artifact, jobs_dir, name="source")
            upload = manifest.checkpoints["upload"]
            manifest.transition_checkpoint(
                "upload", "awaiting_review", upload["revision"], jobs_dir)

            service = JobService(data_dir, app_config_path=data_dir / "app.yml")
            try:
                with patch(
                        "clipmorph.upload_pipeline.UploadPipeline"
                ) as pipeline_type:
                    pipeline_type.return_value.run.return_value = {}
                    service.submit_upload(manifest.job_id)
                    service._futures[f"upload:{manifest.job_id}"].result(
                        timeout=10)

                self.assertEqual(
                    pipeline_type.call_args.kwargs,
                    {"youtube": True, "instagram": True,
                     "tiktok": True, "twitter": True},
                )
                submitted = pipeline_type.call_args.kwargs
                self.assertEqual(sorted(submitted), sorted(SUPPORTED_PLATFORMS))
            finally:
                service.close()


if __name__ == "__main__":
    unittest.main()
