"""Generated by Quality Playbook v1.5.6 - 2026-09-24 - ClipMorph."""

import tempfile
import unittest
from pathlib import Path

from clipmorph.configuration import merge_configuration
from clipmorph.job import JobManifest, source_sha256
from clipmorph.policy import validate_artifact


class FunctionalContractTests(unittest.TestCase):
    def test_cancellation_state_contract(self):
        source = Path("clipmorph/workflow.py").read_text(encoding="utf-8")
        self.assertIn("token.is_cancelled", source)

    def test_cli_web_contract_locations(self):
        self.assertTrue(Path("clipmorph/__main__.py").exists())
        self.assertTrue(Path("clipmorph/workflow.py").exists())

    def test_config_precedence_contract(self):
        defaults = {
            "general": {"no_confirm": False},
            "conversion": {},
            "upload": {"skip": False},
        }
        override = {"general": {"no_confirm": True}}
        merged = merge_configuration(defaults, override)
        self.assertTrue(merged["general"]["no_confirm"])
        self.assertFalse(merged["upload"]["skip"])

    def test_platform_result_contract(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            source = Path(temp_dir) / "source.mp4"
            source.write_bytes(b"source")
            manifest = JobManifest.create(str(source), {}, temp_dir)
            manifest.record_platform("youtube", {"success": True}, temp_dir)
            manifest.record_platform("twitter", {"success": False}, temp_dir)
            loaded = JobManifest.load(manifest.job_id, temp_dir)
            self.assertTrue(loaded.platforms["youtube"]["success"])
            self.assertEqual(loaded.status, "partial_failure")

    def test_policy_transformation_contract(self):
        decision = validate_artifact("twitter", {"duration": 1}, {"title": "x" * 300})
        self.assertEqual(len(decision.metadata["caption"]), 280)
        self.assertIn("caption", decision.transformations[0])

    def test_resume_identity_contract(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            source = Path(temp_dir) / "source.mp4"
            source.write_bytes(b"source")
            manifest = JobManifest.create(str(source), {}, temp_dir)
            self.assertEqual(manifest.source_sha256, source_sha256(source))
            source.write_bytes(b"changed")
            self.assertNotEqual(manifest.source_sha256, source_sha256(source))


if __name__ == "__main__":
    unittest.main()