"""Regression tests for confirmed bugs, generated by the Quality Playbook.

BUG-001: a platform with no per-platform participation override must upload
when the job-level ``upload.skip`` is false, never zero platforms. The
selection map's ``include``/``exclude`` lists are gone; participation is
``platforms.<platform>.upload.skip``, and an absent entry inherits the
job-level flag.

Regenerated for the layered-configuration contract. The workflow stops
at the pre-upload review gate (`execute_job` transitions upload to
``awaiting_review``); the platform selection itself is applied by
``JobService.submit_upload`` when the accepted draft is submitted, so the
absence-default behavior is asserted at that boundary. Processing and upload
boundaries are mocked; no credentials or network are used.
"""

import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from clipmorph.job import JobManifest
from clipmorph.platforms import SUPPORTED_PLATFORMS
from clipmorph.service import JobService
from clipmorph.workflow import _enabled_platforms


class Bug001RegressionTests(unittest.TestCase):
    def test_workflow_absent_participation_entry_resolves_to_all_platforms(self):
        self.assertEqual(
            _enabled_platforms({"upload": {"skip": False}}),
            list(SUPPORTED_PLATFORMS))

    def test_absent_participation_entry_enables_all_platforms(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            source = Path(temp_dir) / "input.mp4"
            source.write_bytes(b"video")
            data_dir = Path(temp_dir)
            jobs_dir = data_dir / "jobs"

            configuration = {
                "general": {"source": "input.mp4"},
                "conversion": {"skip": True, "subtitles": {"skip": True}},
                "upload": {
                    "skip": False,
                    "content": {"title": "Regression clip"},
                },
            }
            manifest = JobManifest.create(str(source), configuration, jobs_dir)
            source_artifact = manifest.source_path
            manifest.set_artifact(source_artifact, jobs_dir, name="source")
            # The upload checkpoint starts as ``pending`` (upload.skip is
            # false) and the workflow stops at the pre-upload review gate.
            manifest.transition_checkpoint(
                "upload", "awaiting_review",
                manifest.checkpoints["upload"]["revision"], jobs_dir)

            service = JobService(data_dir, app_config_path=data_dir / "app.yml")
            try:
                with patch(
                        "clipmorph.upload_pipeline.UploadPipeline"
                ) as pipeline_type:
                    pipeline_type.return_value.run.return_value = {}
                    service.submit_upload(manifest.job_id)
                    service._futures[f"upload:{manifest.job_id}"].result(
                        timeout=10)

                submitted = pipeline_type.call_args.kwargs
                self.assertEqual(
                    {key: value for key, value in submitted.items()
                     if key != "progress_callback"},
                    {"youtube": True, "instagram": True,
                     "tiktok": True, "twitter": True, "facebook": True},
                )
                self.assertIsNotNone(submitted.get("progress_callback"))
                self.assertEqual(
                    sorted(key for key in submitted if key != "progress_callback"),
                    sorted(SUPPORTED_PLATFORMS),
                )
            finally:
                service.close()


if __name__ == "__main__":
    unittest.main()
