"""Generated by Quality Playbook v1.5.6 - regression tests for confirmed bugs."""

import unittest
from unittest.mock import patch

from clipmorph.service import CancellationToken
from clipmorph.workflow import execute_job


class FakeManifest:
    job_id = "job"
    source_path = "input.mp4"
    configuration = {"no_conversion": True, "no_upload": False, "upload_to": []}

    def set_step(self, *_args, **_kwargs):
        pass

    def set_artifact(self, *_args, **_kwargs):
        pass

    def record_platform(self, *_args, **_kwargs):
        pass


class RegressionTests(unittest.TestCase):
    @unittest.expectedFailure
    def test_bug_001_empty_upload_list_means_all_platforms(self):
        with patch("clipmorph.workflow.configure_ffmpeg"), \
                patch("clipmorph.workflow.FFmpegRunner") as runner_type, \
                patch("clipmorph.workflow.PreflightValidator") as validator_type, \
                patch("clipmorph.upload_pipeline.UploadPipeline") as pipeline_type:
            runner_type.return_value.get_video_info.return_value = {
                "streams": [{"codec_type": "video", "width": 1920, "height": 1080}],
                "format": {"duration": 10},
            }
            pipeline_type.return_value.run.return_value = {}
            execute_job(FakeManifest(), CancellationToken(), "jobs")

        self.assertEqual(
            pipeline_type.call_args.kwargs,
            {"youtube": True, "instagram": True, "tiktok": True, "twitter": True},
        )


if __name__ == "__main__":
    unittest.main()