name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version number (without v prefix, format: X.Y.Z)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}  # PAT for checkout and push
    
    - name: Validate version format
      run: |
        VERSION="${{ github.event.inputs.version }}"
        
        # Check if version matches X.Y.Z format (where X, Y, Z are numbers)
        if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "❌ Error: Version must be in format X.Y.Z (e.g., 1.2.3)"
          echo "Received: $VERSION"
          exit 1
        fi
        
        echo "✓ Version format is valid: $VERSION"
    
    - name: Check if version tag exists
      run: |
        if git rev-parse "v${{ github.event.inputs.version }}" >/dev/null 2>&1; then
          echo "❌ Error: Version v${{ github.event.inputs.version }} already exists"
          exit 1
        fi
        
        echo "✓ Version tag does not exist yet"
        
    - name: Update version and create tag
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # Update version file
        echo "__version__ = \"${{ github.event.inputs.version }}\"" > clipmorph/__version__.py
        
        # Commit changes (allow empty if no changes)
        git add clipmorph/__version__.py
        git diff --staged --quiet || git commit -m "Release v${{ github.event.inputs.version }}"
        
        # Create tag
        git tag -a "v${{ github.event.inputs.version }}" -m "Release v${{ github.event.inputs.version }}"
        
        # Push changes (PAT is already configured from checkout)
        git push origin main || echo "No changes to push to main"
        
        # Push the tag - this will trigger build.yml automatically
        git push origin "v${{ github.event.inputs.version }}"